export const SPECIAL_RULE_KEYS = {
  AMBUSH: "ambush",
  EXPLODE: "explode",
  FAST: "fast",
  FLYING: "flying",
  IMMOBILE: "immobile",
  HERO: "hero",
  LIMITED: "limited",
  SCOUT: "scout",
  SLOW: "slow",
  STEALTH: "stealth",
  STRIDER: "strider",
  TOUGH: "tough",
};

export const RELEVANT_RULE_KEYS_FOR_ATTACHMENT = [
  SPECIAL_RULE_KEYS.AMBUSH,
  SPECIAL_RULE_KEYS.EXPLODE,
  SPECIAL_RULE_KEYS.FAST,
  SPECIAL_RULE_KEYS.FLYING,
  SPECIAL_RULE_KEYS.IMMOBILE,
  SPECIAL_RULE_KEYS.SCOUT,
  SPECIAL_RULE_KEYS.SLOW,
  SPECIAL_RULE_KEYS.STEALTH,
  SPECIAL_RULE_KEYS.STRIDER,
];
